# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rickfatecdocker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e48b538a03034de3ae5214191e274fd0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_56603a45c24b4305ba99214145cb5d40 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e48b538a03034de3ae5214191e274fd0 }}/ubuntu:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rickfatecdocker'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ba8f5130df3d4546b3e80f5bbb333a80 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e48b538a03034de3ae5214191e274fd0 }}/ubuntu:${{ github.sha }}'