# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - testecontainerfatec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e7095fdb6f69495d9fa653ea2bc00214 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c11933669caa41d4abba4fce828ed25a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e7095fdb6f69495d9fa653ea2bc00214 }}/testecontainer:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'testecontainerfatec'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_01d71bff8a9b40e2b274d212c0af372c }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e7095fdb6f69495d9fa653ea2bc00214 }}/testecontainer:${{ github.sha }}'